title: Philipp Schwarz
author: Philipp Schwarz
email: philipp.schw@gmail.com
description: >- # this means to ignore newlines until "show_exerpts:"
  Machine Learning Engineer & Data Scientist  with strong statistical 
  modeling and programming skills. I prefer working in a high-performance environment and in an
  interdisciplinary team. Reach out to me if you got a project that is
  unprecedented, and you need a pragmatic guy that delivers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://philippschw.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:title/

plainwhite:
  name: Philipp Schwarz
  tagline: Senior Data Scientist - Focus on Computer Vision
  analytics_id: "UA-167457440-1"
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github:  philippschw
    linkedIn: in/philippschw
    twitter:  philippschw


# Build settings
markdown: kramdown
remote_theme: thelehhman/plainwhite-jekyll
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-redirect-from


